import type { Metadata } from "next";
import Header from "@/app/src/components/organisms/layout/Header";
import Footer from "@/app/src/components/organisms/layout/Footer";
import "@fontsource-variable/playfair-display";
import "@fontsource-variable/inter";

import "./globals.css";

export const metadata: Metadata = {
  title: "Chloe Author Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="fr">
      <body className="font-inter min-h-screen flex flex-col">
        <Header />
        <main className="flex-1 container mx-auto px-4">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
