import type { Metadata } from "next";
import Header from "@/app/src/components/organisms/layout/Header";
import Footer from "@/app/src/components/organisms/layout/Footer";
import { getNavigation } from "@/app/src/lib/navigation";
import { getSiteSettings } from "@/app/src/lib/settings";
import { getRomans } from "@/app/src/lib/romans";
import "@fontsource-variable/playfair-display";
import "@fontsource-variable/inter";

import "./globals.css";

export const metadata: Metadata = {
  title: "Chloe Author Site",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [navigation, settings, romans] = await Promise.all([
    getNavigation(),
    getSiteSettings(),
    getRomans(),
  ]);
  const romanLinks = romans.slice(0, 6).map((roman) => ({
    label: roman.title,
    href: `/romans/${roman.slug}`,
  }));

  return (
   <html lang="fr">
      <body className="font-body min-h-screen flex flex-col">
        <Header navigation={navigation} romanLinks={romanLinks} settings={settings} />
        <main className="flex-1 container mx-auto px-4">
          {children}
        </main>
        <Footer navigation={navigation} settings={settings} />
      </body>
    </html>
  );
}
